services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:4000
    volumes:
      - ./frontend:/app

  backend:
    build:
      context: ./backend
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
      - NODE_ENV=development
      - FIREBASE_PROJECT_ID=roadside-rescue-b24bb
      - FIREBASE_SERVICE_ACCOUNT_KEY=/app/backend/roadside-rescue-b24bb-firebase-adminsdk-daj4z-768f107fa9.json
    volumes:
      - ./backend/roadside-rescue-b24bb-firebase-adminsdk-daj4z-768f107fa9.json:/app/backend/roadside-rescue-b24bb-firebase-adminsdk-daj4z-768f107fa9.json
      - ./backend:/app